# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_landscapestatistics.ui'
#
# Created: Mon Feb 18 21:40:35 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Lecos(object):
    def setupUi(self, Lecos):
        Lecos.setObjectName(_fromUtf8("Lecos"))
        Lecos.resize(498, 508)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Lecos.sizePolicy().hasHeightForWidth())
        Lecos.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Lecos.setWindowIcon(icon)
        Lecos.setAutoFillBackground(False)
        self.gridLayoutWidget = QtGui.QWidget(Lecos)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 481))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 447, 138))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.cbRaster = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cbRaster.setObjectName(_fromUtf8("cbRaster"))
        self.gridLayout_2.addWidget(self.cbRaster, 1, 0, 1, 2)
        self.where2Save = QtGui.QToolButton(self.gridLayoutWidget_2)
        self.where2Save.setEnabled(False)
        self.where2Save.setCheckable(False)
        self.where2Save.setObjectName(_fromUtf8("where2Save"))
        self.gridLayout_2.addWidget(self.where2Save, 5, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_3.setEnabled(True)
        self.line_3.setMaximumSize(QtCore.QSize(168, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 3, 1, 1, 1)
        self.rbDirect = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.rbDirect.setChecked(True)
        self.rbDirect.setAutoRepeat(False)
        self.rbDirect.setObjectName(_fromUtf8("rbDirect"))
        self.gridLayout_2.addWidget(self.rbDirect, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 3, 2, 1, 3)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 3, 1, 1)
        self.sp_cellsize = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sp_cellsize.setMaximum(999)
        self.sp_cellsize.setProperty("value", 0)
        self.sp_cellsize.setObjectName(_fromUtf8("sp_cellsize"))
        self.gridLayout_2.addWidget(self.sp_cellsize, 1, 4, 1, 1)
        self.rbSAVE = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.rbSAVE.setObjectName(_fromUtf8("rbSAVE"))
        self.gridLayout_2.addWidget(self.rbSAVE, 5, 0, 1, 1)
        self.SaveCsv = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.SaveCsv.setEnabled(False)
        self.SaveCsv.setReadOnly(True)
        self.SaveCsv.setObjectName(_fromUtf8("SaveCsv"))
        self.gridLayout_2.addWidget(self.SaveCsv, 5, 2, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.NoDataVal = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.NoDataVal.setObjectName(_fromUtf8("NoDataVal"))
        self.gridLayout_2.addWidget(self.NoDataVal, 0, 4, 1, 1)
        self.MetricTab = QtGui.QTabWidget(self.groupBox)
        self.MetricTab.setGeometry(QtCore.QRect(10, 170, 461, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MetricTab.sizePolicy().hasHeightForWidth())
        self.MetricTab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.MetricTab.setFont(font)
        self.MetricTab.setTabPosition(QtGui.QTabWidget.North)
        self.MetricTab.setTabShape(QtGui.QTabWidget.Rounded)
        self.MetricTab.setTabsClosable(False)
        self.MetricTab.setMovable(False)
        self.MetricTab.setObjectName(_fromUtf8("MetricTab"))
        self.singleMet = QtGui.QWidget()
        self.singleMet.setObjectName(_fromUtf8("singleMet"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.singleMet)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 451, 229))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.SingleMetric = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.SingleMetric.setMaxVisibleItems(100)
        self.SingleMetric.setObjectName(_fromUtf8("SingleMetric"))
        self.verticalLayout_2.addWidget(self.SingleMetric)
        self.SingleMetricHelp = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        self.SingleMetricHelp.setEnabled(False)
        self.SingleMetricHelp.setObjectName(_fromUtf8("SingleMetricHelp"))
        self.verticalLayout_2.addWidget(self.SingleMetricHelp)
        self.MetricTab.addTab(self.singleMet, _fromUtf8(""))
        self.multiMet = QtGui.QWidget()
        self.multiMet.setObjectName(_fromUtf8("multiMet"))
        self.verticalLayoutWidget = QtGui.QWidget(self.multiMet)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 50, 87, 128))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_right = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_right.setObjectName(_fromUtf8("btn_right"))
        self.verticalLayout.addWidget(self.btn_right)
        self.btn_left = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_left.setObjectName(_fromUtf8("btn_left"))
        self.verticalLayout.addWidget(self.btn_left)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.list_right = QtGui.QListWidget(self.multiMet)
        self.list_right.setGeometry(QtCore.QRect(260, 30, 191, 171))
        self.list_right.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.list_right.setObjectName(_fromUtf8("list_right"))
        self.list_left = QtGui.QListWidget(self.multiMet)
        self.list_left.setGeometry(QtCore.QRect(10, 30, 171, 171))
        self.list_left.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.list_left.setObjectName(_fromUtf8("list_left"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.multiMet)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 194, 28))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.SelectAll = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.SelectAll.setObjectName(_fromUtf8("SelectAll"))
        self.horizontalLayout_2.addWidget(self.SelectAll)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.rlistCounter = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.rlistCounter.setFont(font)
        self.rlistCounter.setTextFormat(QtCore.Qt.AutoText)
        self.rlistCounter.setScaledContents(False)
        self.rlistCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rlistCounter.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.rlistCounter.setObjectName(_fromUtf8("rlistCounter"))
        self.horizontalLayout_2.addWidget(self.rlistCounter)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.multiMet)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(260, 200, 194, 28))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.SelectAll_2 = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.SelectAll_2.setObjectName(_fromUtf8("SelectAll_2"))
        self.horizontalLayout_3.addWidget(self.SelectAll_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.rlistCounter_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.rlistCounter_2.setFont(font)
        self.rlistCounter_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.rlistCounter_2.setFrameShadow(QtGui.QFrame.Plain)
        self.rlistCounter_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rlistCounter_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.rlistCounter_2.setObjectName(_fromUtf8("rlistCounter_2"))
        self.horizontalLayout_3.addWidget(self.rlistCounter_2)
        self.label_4 = QtGui.QLabel(self.multiMet)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.multiMet)
        self.label_5.setGeometry(QtCore.QRect(330, 10, 59, 15))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.MetricTab.addTab(self.multiMet, _fromUtf8(""))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(0, 440, 479, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(Lecos)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 460, 481, 33))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.btn_About = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_About.setObjectName(_fromUtf8("btn_About"))
        self.horizontalLayout.addWidget(self.btn_About)
        self.bt_Accept = QtGui.QDialogButtonBox(self.horizontalLayoutWidget)
        self.bt_Accept.setOrientation(QtCore.Qt.Horizontal)
        self.bt_Accept.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bt_Accept.setCenterButtons(True)
        self.bt_Accept.setObjectName(_fromUtf8("bt_Accept"))
        self.horizontalLayout.addWidget(self.bt_Accept)

        self.retranslateUi(Lecos)
        self.MetricTab.setCurrentIndex(1)
        QtCore.QObject.connect(self.bt_Accept, QtCore.SIGNAL(_fromUtf8("accepted()")), Lecos.accept)
        QtCore.QObject.connect(self.bt_Accept, QtCore.SIGNAL(_fromUtf8("rejected()")), Lecos.reject)
        QtCore.QMetaObject.connectSlotsByName(Lecos)

    def retranslateUi(self, Lecos):
        Lecos.setWindowTitle(QtGui.QApplication.translate("Lecos", "Landcover Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Lecos", "Landscape Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Lecos", "No-data:", None, QtGui.QApplication.UnicodeUTF8))
        self.where2Save.setText(QtGui.QApplication.translate("Lecos", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDirect.setText(QtGui.QApplication.translate("Lecos", "Direct value output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Lecos", "Landcover grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Lecos", "Cellsize:", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSAVE.setText(QtGui.QApplication.translate("Lecos", "Save results as csv", None, QtGui.QApplication.UnicodeUTF8))
        self.MetricTab.setTabText(self.MetricTab.indexOf(self.singleMet), QtGui.QApplication.translate("Lecos", "Calculate Metric", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_right.setText(QtGui.QApplication.translate("Lecos", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_left.setText(QtGui.QApplication.translate("Lecos", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectAll.setText(QtGui.QApplication.translate("Lecos", "Select all/none", None, QtGui.QApplication.UnicodeUTF8))
        self.rlistCounter.setText(QtGui.QApplication.translate("Lecos", "(0)", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectAll_2.setText(QtGui.QApplication.translate("Lecos", "Select all/none", None, QtGui.QApplication.UnicodeUTF8))
        self.rlistCounter_2.setText(QtGui.QApplication.translate("Lecos", "(0)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Lecos", "Metric list", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Lecos", "Joblist", None, QtGui.QApplication.UnicodeUTF8))
        self.MetricTab.setTabText(self.MetricTab.indexOf(self.multiMet), QtGui.QApplication.translate("Lecos", "Select multiple Metrics", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_About.setText(QtGui.QApplication.translate("Lecos", "About", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
