# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_PolygonPerLandCover.ui'
#
# Created: Fri Mar  8 18:22:27 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BatchDialog(object):
    def setupUi(self, BatchDialog):
        BatchDialog.setObjectName(_fromUtf8("BatchDialog"))
        BatchDialog.setWindowModality(QtCore.Qt.WindowModal)
        BatchDialog.resize(578, 348)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BatchDialog.sizePolicy().hasHeightForWidth())
        BatchDialog.setSizePolicy(sizePolicy)
        BatchDialog.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/icon_batchCover.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BatchDialog.setWindowIcon(icon)
        BatchDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line = QtGui.QFrame(BatchDialog)
        self.line.setGeometry(QtCore.QRect(10, 90, 561, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(BatchDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 110, 561, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Raised)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setMargin(10)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cb_Classified = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.cb_Classified.setObjectName(_fromUtf8("cb_Classified"))
        self.cb_Classified.addItem(_fromUtf8(""))
        self.cb_Classified.setItemText(0, _fromUtf8(""))
        self.cb_Classified.addItem(_fromUtf8(""))
        self.cb_Classified.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cb_Classified)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.stackWidget = QtGui.QStackedWidget(BatchDialog)
        self.stackWidget.setGeometry(QtCore.QRect(10, 160, 561, 141))
        self.stackWidget.setFrameShape(QtGui.QFrame.Box)
        self.stackWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackWidget.setObjectName(_fromUtf8("stackWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.page)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 541, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cb_LClass = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.cb_LClass.setObjectName(_fromUtf8("cb_LClass"))
        self.horizontalLayout_4.addWidget(self.cb_LClass)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 291, 16))
        self.label_5.setFrameShape(QtGui.QFrame.Panel)
        self.label_5.setFrameShadow(QtGui.QFrame.Raised)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.page)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 90, 541, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.rb_LCnumber = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        self.rb_LCnumber.setChecked(True)
        self.rb_LCnumber.setObjectName(_fromUtf8("rb_LCnumber"))
        self.horizontalLayout_5.addWidget(self.rb_LCnumber)
        self.rb_LCprop = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        self.rb_LCprop.setObjectName(_fromUtf8("rb_LCprop"))
        self.horizontalLayout_5.addWidget(self.rb_LCprop)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.line_2 = QtGui.QFrame(self.page)
        self.line_2.setGeometry(QtCore.QRect(10, 70, 541, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.stackWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 291, 16))
        self.label_6.setFrameShape(QtGui.QFrame.Panel)
        self.label_6.setFrameShadow(QtGui.QFrame.Raised)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 531, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 531, 74))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rb_Umean = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Umean.setFont(font)
        self.rb_Umean.setObjectName(_fromUtf8("rb_Umean"))
        self.gridLayout.addWidget(self.rb_Umean, 0, 0, 1, 1)
        self.rb_Usum = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Usum.setFont(font)
        self.rb_Usum.setChecked(True)
        self.rb_Usum.setObjectName(_fromUtf8("rb_Usum"))
        self.gridLayout.addWidget(self.rb_Usum, 1, 0, 1, 1)
        self.rb_Ustd = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Ustd.setFont(font)
        self.rb_Ustd.setObjectName(_fromUtf8("rb_Ustd"))
        self.gridLayout.addWidget(self.rb_Ustd, 0, 1, 1, 1)
        self.rb_Umed = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Umed.setFont(font)
        self.rb_Umed.setObjectName(_fromUtf8("rb_Umed"))
        self.gridLayout.addWidget(self.rb_Umed, 1, 1, 1, 1)
        self.rb_Uuqt = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Uuqt.setFont(font)
        self.rb_Uuqt.setObjectName(_fromUtf8("rb_Uuqt"))
        self.gridLayout.addWidget(self.rb_Uuqt, 1, 3, 1, 1)
        self.rb_Umin = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Umin.setFont(font)
        self.rb_Umin.setObjectName(_fromUtf8("rb_Umin"))
        self.gridLayout.addWidget(self.rb_Umin, 1, 2, 1, 1)
        self.rb_Umax = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Umax.setFont(font)
        self.rb_Umax.setObjectName(_fromUtf8("rb_Umax"))
        self.gridLayout.addWidget(self.rb_Umax, 0, 2, 1, 1)
        self.rb_Ulqt = QtGui.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rb_Ulqt.setFont(font)
        self.rb_Ulqt.setObjectName(_fromUtf8("rb_Ulqt"))
        self.gridLayout.addWidget(self.rb_Ulqt, 0, 3, 1, 1)
        self.stackWidget.addWidget(self.page_2)
        self.label = QtGui.QLabel(BatchDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 29))
        self.label.setObjectName(_fromUtf8("label"))
        self.cb_Raster = QtGui.QComboBox(BatchDialog)
        self.cb_Raster.setGeometry(QtCore.QRect(190, 10, 381, 27))
        self.cb_Raster.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_Raster.setObjectName(_fromUtf8("cb_Raster"))
        self.label_2 = QtGui.QLabel(BatchDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 161, 29))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cb_Vector = QtGui.QComboBox(BatchDialog)
        self.cb_Vector.setGeometry(QtCore.QRect(190, 50, 381, 27))
        self.cb_Vector.setObjectName(_fromUtf8("cb_Vector"))
        self.lab_feat = QtGui.QLabel(BatchDialog)
        self.lab_feat.setGeometry(QtCore.QRect(440, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lab_feat.setFont(font)
        self.lab_feat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lab_feat.setText(_fromUtf8(""))
        self.lab_feat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lab_feat.setObjectName(_fromUtf8("lab_feat"))
        self.label_7 = QtGui.QLabel(BatchDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 300, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayoutWidget = QtGui.QWidget(BatchDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 310, 269, 29))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_About = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_About.setObjectName(_fromUtf8("btn_About"))
        self.horizontalLayout.addWidget(self.btn_About)
        self.startButtons = QtGui.QDialogButtonBox(self.horizontalLayoutWidget)
        self.startButtons.setOrientation(QtCore.Qt.Horizontal)
        self.startButtons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.startButtons.setObjectName(_fromUtf8("startButtons"))
        self.horizontalLayout.addWidget(self.startButtons)

        self.retranslateUi(BatchDialog)
        self.stackWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.startButtons, QtCore.SIGNAL(_fromUtf8("accepted()")), BatchDialog.accept)
        QtCore.QObject.connect(self.startButtons, QtCore.SIGNAL(_fromUtf8("rejected()")), BatchDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BatchDialog)

    def retranslateUi(self, BatchDialog):
        BatchDialog.setWindowTitle(QtGui.QApplication.translate("BatchDialog", "Raster values for polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BatchDialog", "Raster classified?", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Classified.setItemText(1, QtGui.QApplication.translate("BatchDialog", "YES", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Classified.setItemText(2, QtGui.QApplication.translate("BatchDialog", "NO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BatchDialog", "Choose Class:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BatchDialog", "Options for classified Raster layers", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_LCnumber.setText(QtGui.QApplication.translate("BatchDialog", "Calculate Number of cells", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_LCprop.setText(QtGui.QApplication.translate("BatchDialog", "Calculate proportion of Landcover", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BatchDialog", "Options for unclassified Raster layers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BatchDialog", "Calculate:", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Umean.setText(QtGui.QApplication.translate("BatchDialog", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Usum.setText(QtGui.QApplication.translate("BatchDialog", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Ustd.setText(QtGui.QApplication.translate("BatchDialog", "Standard Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Umed.setText(QtGui.QApplication.translate("BatchDialog", " Median", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Uuqt.setText(QtGui.QApplication.translate("BatchDialog", "Upper Quantile (75%)", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Umin.setText(QtGui.QApplication.translate("BatchDialog", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Umax.setText(QtGui.QApplication.translate("BatchDialog", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Ulqt.setText(QtGui.QApplication.translate("BatchDialog", "Lower Quantile (25%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BatchDialog", "Raster layer :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BatchDialog", "Vector layer (polygon) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BatchDialog", "<html><head/><body>Results will be added to the <br>vector layer attribute table!</body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_About.setText(QtGui.QApplication.translate("BatchDialog", "About", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
