# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caioh\src\LecoS\ui\dlg_landscapestatistics.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Lecos(object):
    def setupUi(self, Lecos):
        Lecos.setObjectName("Lecos")
        Lecos.resize(498, 508)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Lecos.sizePolicy().hasHeightForWidth())
        Lecos.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Lecos.setWindowIcon(icon)
        Lecos.setAutoFillBackground(False)
        self.gridLayoutWidget = QtWidgets.QWidget(Lecos)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 447, 138))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.cbRaster = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cbRaster.setObjectName("cbRaster")
        self.gridLayout_2.addWidget(self.cbRaster, 1, 0, 1, 2)
        self.where2Save = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.where2Save.setEnabled(False)
        self.where2Save.setCheckable(False)
        self.where2Save.setObjectName("where2Save")
        self.gridLayout_2.addWidget(self.where2Save, 5, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_3.setEnabled(True)
        self.line_3.setMaximumSize(QtCore.QSize(168, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 1, 1, 1)
        self.rbDirect = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.rbDirect.setChecked(True)
        self.rbDirect.setAutoRepeat(False)
        self.rbDirect.setObjectName("rbDirect")
        self.gridLayout_2.addWidget(self.rbDirect, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 3, 2, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 3, 1, 1)
        self.sp_cellsize = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sp_cellsize.setMaximum(999)
        self.sp_cellsize.setProperty("value", 0)
        self.sp_cellsize.setObjectName("sp_cellsize")
        self.gridLayout_2.addWidget(self.sp_cellsize, 1, 4, 1, 1)
        self.rbSAVE = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.rbSAVE.setObjectName("rbSAVE")
        self.gridLayout_2.addWidget(self.rbSAVE, 5, 0, 1, 1)
        self.SaveCsv = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.SaveCsv.setEnabled(False)
        self.SaveCsv.setReadOnly(True)
        self.SaveCsv.setObjectName("SaveCsv")
        self.gridLayout_2.addWidget(self.SaveCsv, 5, 2, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.NoDataVal = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.NoDataVal.setObjectName("NoDataVal")
        self.gridLayout_2.addWidget(self.NoDataVal, 0, 4, 1, 1)
        self.MetricTab = QtWidgets.QTabWidget(self.groupBox)
        self.MetricTab.setGeometry(QtCore.QRect(10, 170, 461, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MetricTab.sizePolicy().hasHeightForWidth())
        self.MetricTab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.MetricTab.setFont(font)
        self.MetricTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.MetricTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MetricTab.setTabsClosable(False)
        self.MetricTab.setMovable(False)
        self.MetricTab.setObjectName("MetricTab")
        self.singleMet = QtWidgets.QWidget()
        self.singleMet.setObjectName("singleMet")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.singleMet)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 451, 229))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SingleMetric = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.SingleMetric.setMaxVisibleItems(100)
        self.SingleMetric.setObjectName("SingleMetric")
        self.verticalLayout_2.addWidget(self.SingleMetric)
        self.SingleMetricHelp = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.SingleMetricHelp.setEnabled(False)
        self.SingleMetricHelp.setObjectName("SingleMetricHelp")
        self.verticalLayout_2.addWidget(self.SingleMetricHelp)
        self.MetricTab.addTab(self.singleMet, "")
        self.multiMet = QtWidgets.QWidget()
        self.multiMet.setObjectName("multiMet")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.multiMet)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 50, 87, 128))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_right = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_right.setObjectName("btn_right")
        self.verticalLayout.addWidget(self.btn_right)
        self.btn_left = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_left.setObjectName("btn_left")
        self.verticalLayout.addWidget(self.btn_left)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.list_right = QtWidgets.QListWidget(self.multiMet)
        self.list_right.setGeometry(QtCore.QRect(260, 30, 191, 171))
        self.list_right.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.list_right.setObjectName("list_right")
        self.list_left = QtWidgets.QListWidget(self.multiMet)
        self.list_left.setGeometry(QtCore.QRect(10, 30, 171, 171))
        self.list_left.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.list_left.setObjectName("list_left")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.multiMet)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 194, 28))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SelectAll = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.SelectAll.setObjectName("SelectAll")
        self.horizontalLayout_2.addWidget(self.SelectAll)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.rlistCounter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.rlistCounter.setFont(font)
        self.rlistCounter.setTextFormat(QtCore.Qt.AutoText)
        self.rlistCounter.setScaledContents(False)
        self.rlistCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rlistCounter.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.rlistCounter.setObjectName("rlistCounter")
        self.horizontalLayout_2.addWidget(self.rlistCounter)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.multiMet)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(260, 200, 194, 28))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SelectAll_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.SelectAll_2.setObjectName("SelectAll_2")
        self.horizontalLayout_3.addWidget(self.SelectAll_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.rlistCounter_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.rlistCounter_2.setFont(font)
        self.rlistCounter_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rlistCounter_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rlistCounter_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rlistCounter_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.rlistCounter_2.setObjectName("rlistCounter_2")
        self.horizontalLayout_3.addWidget(self.rlistCounter_2)
        self.label_4 = QtWidgets.QLabel(self.multiMet)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.multiMet)
        self.label_5.setGeometry(QtCore.QRect(330, 10, 59, 15))
        self.label_5.setObjectName("label_5")
        self.MetricTab.addTab(self.multiMet, "")
        self.landMet = QtWidgets.QWidget()
        self.landMet.setObjectName("landMet")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.landMet)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 441, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.LandscapeBox = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.LandscapeBox.setContentsMargins(0, 0, 0, 0)
        self.LandscapeBox.setObjectName("LandscapeBox")
        self.ch_LC4 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC4.setObjectName("ch_LC4")
        self.LandscapeBox.addWidget(self.ch_LC4, 4, 0, 1, 1)
        self.ch_LC1 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC1.setObjectName("ch_LC1")
        self.LandscapeBox.addWidget(self.ch_LC1, 1, 0, 1, 1)
        self.ch_LC2 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC2.setObjectName("ch_LC2")
        self.LandscapeBox.addWidget(self.ch_LC2, 2, 0, 1, 1)
        self.ch_LC3 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC3.setObjectName("ch_LC3")
        self.LandscapeBox.addWidget(self.ch_LC3, 3, 0, 1, 1)
        self.ch_LC5 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC5.setObjectName("ch_LC5")
        self.LandscapeBox.addWidget(self.ch_LC5, 1, 1, 1, 1)
        self.ch_LC7 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC7.setObjectName("ch_LC7")
        self.LandscapeBox.addWidget(self.ch_LC7, 3, 1, 1, 1)
        self.ch_LC6 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC6.setObjectName("ch_LC6")
        self.LandscapeBox.addWidget(self.ch_LC6, 2, 1, 1, 1)
        self.ch_LC8 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ch_LC8.setObjectName("ch_LC8")
        self.LandscapeBox.addWidget(self.ch_LC8, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.LandscapeBox.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.landMet)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 140, 163, 95))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.ch_div1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.ch_div1.setObjectName("ch_div1")
        self.verticalLayout_3.addWidget(self.ch_div1)
        self.ch_div2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.ch_div2.setObjectName("ch_div2")
        self.verticalLayout_3.addWidget(self.ch_div2)
        self.ch_div3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.ch_div3.setObjectName("ch_div3")
        self.verticalLayout_3.addWidget(self.ch_div3)
        self.MetricTab.addTab(self.landMet, "")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(0, 440, 479, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Lecos)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 460, 481, 34))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.btn_About = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_About.setIcon(icon1)
        self.btn_About.setIconSize(QtCore.QSize(12, 12))
        self.btn_About.setObjectName("btn_About")
        self.horizontalLayout.addWidget(self.btn_About)
        self.bt_Accept = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget)
        self.bt_Accept.setOrientation(QtCore.Qt.Horizontal)
        self.bt_Accept.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bt_Accept.setCenterButtons(True)
        self.bt_Accept.setObjectName("bt_Accept")
        self.horizontalLayout.addWidget(self.bt_Accept)

        self.retranslateUi(Lecos)
        self.MetricTab.setCurrentIndex(0)
        self.bt_Accept.accepted.connect(Lecos.accept)
        self.bt_Accept.rejected.connect(Lecos.reject)
        QtCore.QMetaObject.connectSlotsByName(Lecos)

    def retranslateUi(self, Lecos):
        _translate = QtCore.QCoreApplication.translate
        Lecos.setWindowTitle(_translate("Lecos", "Landcover Analysis"))
        self.groupBox.setTitle(_translate("Lecos", "Landscape Statistics"))
        self.label_3.setText(_translate("Lecos", "No-data:"))
        self.where2Save.setText(_translate("Lecos", "..."))
        self.rbDirect.setText(_translate("Lecos", "Direct value output"))
        self.label_2.setText(_translate("Lecos", "Landcover grid"))
        self.label.setText(_translate("Lecos", "Cellsize:"))
        self.rbSAVE.setText(_translate("Lecos", "Save results as csv"))
        self.MetricTab.setTabText(self.MetricTab.indexOf(self.singleMet), _translate("Lecos", "Calculate Metric"))
        self.btn_right.setText(_translate("Lecos", ">"))
        self.btn_left.setText(_translate("Lecos", "<"))
        self.SelectAll.setText(_translate("Lecos", "Select all/none"))
        self.rlistCounter.setText(_translate("Lecos", "(0)"))
        self.SelectAll_2.setText(_translate("Lecos", "Select all/none"))
        self.rlistCounter_2.setText(_translate("Lecos", "(0)"))
        self.label_4.setText(_translate("Lecos", "Metric list"))
        self.label_5.setText(_translate("Lecos", "Joblist"))
        self.MetricTab.setTabText(self.MetricTab.indexOf(self.multiMet), _translate("Lecos", "Select multiple Metrics"))
        self.ch_LC4.setText(_translate("Lecos", "Maximum"))
        self.ch_LC1.setText(_translate("Lecos", "Mean"))
        self.ch_LC2.setText(_translate("Lecos", "Sum"))
        self.ch_LC3.setText(_translate("Lecos", "Minimum"))
        self.ch_LC5.setText(_translate("Lecos", "Standard Deviation"))
        self.ch_LC7.setText(_translate("Lecos", "Median"))
        self.ch_LC6.setText(_translate("Lecos", "Lower Quantile (25%)"))
        self.ch_LC8.setText(_translate("Lecos", "Upper Quantile (25%)"))
        self.label_6.setText(_translate("Lecos", "Zonal statistics"))
        self.label_7.setText(_translate("Lecos", "Diversity"))
        self.ch_div1.setText(_translate("Lecos", "Shannon Index"))
        self.ch_div2.setText(_translate("Lecos", "Shannon equitability"))
        self.ch_div3.setText(_translate("Lecos", "Simpson Index"))
        self.MetricTab.setTabText(self.MetricTab.indexOf(self.landMet), _translate("Lecos", "Landscape Metrics"))
        self.btn_About.setText(_translate("Lecos", "About"))

from .resources_rc import *
