# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_LandscapeModifier.ui'
#
# Created: Fri Mar  8 18:22:28 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LandMod(object):
    def setupUi(self, LandMod):
        LandMod.setObjectName(_fromUtf8("LandMod"))
        LandMod.resize(487, 403)
        LandMod.setMinimumSize(QtCore.QSize(487, 333))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Modify_Res/icons/icon_LandMod.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LandMod.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtGui.QWidget(LandMod)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 471, 29))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cb_Raster = QtGui.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_Raster.sizePolicy().hasHeightForWidth())
        self.cb_Raster.setSizePolicy(sizePolicy)
        self.cb_Raster.setFrame(True)
        self.cb_Raster.setObjectName(_fromUtf8("cb_Raster"))
        self.horizontalLayout.addWidget(self.cb_Raster)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cb_SelClass = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cb_SelClass.setObjectName(_fromUtf8("cb_SelClass"))
        self.horizontalLayout.addWidget(self.cb_SelClass)
        self.line = QtGui.QFrame(LandMod)
        self.line.setGeometry(QtCore.QRect(10, 70, 471, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.box_RasCalc = QtGui.QToolBox(LandMod)
        self.box_RasCalc.setGeometry(QtCore.QRect(10, 80, 471, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_RasCalc.sizePolicy().hasHeightForWidth())
        self.box_RasCalc.setSizePolicy(sizePolicy)
        self.box_RasCalc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_RasCalc.setFrameShape(QtGui.QFrame.StyledPanel)
        self.box_RasCalc.setFrameShadow(QtGui.QFrame.Raised)
        self.box_RasCalc.setObjectName(_fromUtf8("box_RasCalc"))
        self.PatchEdges = QtGui.QWidget()
        self.PatchEdges.setGeometry(QtCore.QRect(0, 0, 469, 119))
        self.PatchEdges.setObjectName(_fromUtf8("PatchEdges"))
        self.helpText = QtGui.QTextEdit(self.PatchEdges)
        self.helpText.setGeometry(QtCore.QRect(290, 0, 171, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpText.sizePolicy().hasHeightForWidth())
        self.helpText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.helpText.setFont(font)
        self.helpText.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.helpText.setFrameShape(QtGui.QFrame.WinPanel)
        self.helpText.setLineWidth(0)
        self.helpText.setMidLineWidth(0)
        self.helpText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.helpText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.helpText.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.helpText.setReadOnly(True)
        self.helpText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.helpText.setObjectName(_fromUtf8("helpText"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.PatchEdges)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 160, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sp_EdgeMult = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.sp_EdgeMult.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sp_EdgeMult.setMinimum(1)
        self.sp_EdgeMult.setProperty("value", 1)
        self.sp_EdgeMult.setObjectName(_fromUtf8("sp_EdgeMult"))
        self.horizontalLayout_3.addWidget(self.sp_EdgeMult)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.CellsizeLine = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.CellsizeLine.setAlignment(QtCore.Qt.AlignCenter)
        self.CellsizeLine.setReadOnly(True)
        self.CellsizeLine.setObjectName(_fromUtf8("CellsizeLine"))
        self.horizontalLayout_3.addWidget(self.CellsizeLine)
        self.label_4 = QtGui.QLabel(self.PatchEdges)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Modify_Res/icons/img_EdgeExtract.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.box_RasCalc.addItem(self.PatchEdges, icon1, _fromUtf8(""))
        self.IsoMaxMinPatch = QtGui.QWidget()
        self.IsoMaxMinPatch.setGeometry(QtCore.QRect(0, 0, 469, 119))
        self.IsoMaxMinPatch.setObjectName(_fromUtf8("IsoMaxMinPatch"))
        self.helpText_2 = QtGui.QTextEdit(self.IsoMaxMinPatch)
        self.helpText_2.setGeometry(QtCore.QRect(290, 0, 171, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpText_2.sizePolicy().hasHeightForWidth())
        self.helpText_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.helpText_2.setFont(font)
        self.helpText_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.helpText_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.helpText_2.setLineWidth(0)
        self.helpText_2.setMidLineWidth(0)
        self.helpText_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.helpText_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.helpText_2.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.helpText_2.setReadOnly(True)
        self.helpText_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.helpText_2.setObjectName(_fromUtf8("helpText_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.IsoMaxMinPatch)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 141, 91))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rb_MaxMin1 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rb_MaxMin1.setChecked(False)
        self.rb_MaxMin1.setObjectName(_fromUtf8("rb_MaxMin1"))
        self.verticalLayout.addWidget(self.rb_MaxMin1)
        self.rb_MaxMin2 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rb_MaxMin2.setChecked(True)
        self.rb_MaxMin2.setObjectName(_fromUtf8("rb_MaxMin2"))
        self.verticalLayout.addWidget(self.rb_MaxMin2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Modify_Res/icons/img_MaxMin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.box_RasCalc.addItem(self.IsoMaxMinPatch, icon2, _fromUtf8(""))
        self.IncDecLand = QtGui.QWidget()
        self.IncDecLand.setGeometry(QtCore.QRect(0, 0, 469, 119))
        self.IncDecLand.setObjectName(_fromUtf8("IncDecLand"))
        self.helpText_3 = QtGui.QTextEdit(self.IncDecLand)
        self.helpText_3.setGeometry(QtCore.QRect(290, 0, 171, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpText_3.sizePolicy().hasHeightForWidth())
        self.helpText_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.helpText_3.setFont(font)
        self.helpText_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.helpText_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.helpText_3.setLineWidth(0)
        self.helpText_3.setMidLineWidth(0)
        self.helpText_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.helpText_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.helpText_3.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.helpText_3.setReadOnly(True)
        self.helpText_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.helpText_3.setObjectName(_fromUtf8("helpText_3"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.IncDecLand)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(19, 9, 231, 81))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.sp_IncDecAm = QtGui.QSpinBox(self.horizontalLayoutWidget_4)
        self.sp_IncDecAm.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sp_IncDecAm.setPrefix(_fromUtf8(""))
        self.sp_IncDecAm.setMinimum(1)
        self.sp_IncDecAm.setProperty("value", 1)
        self.sp_IncDecAm.setObjectName(_fromUtf8("sp_IncDecAm"))
        self.horizontalLayout_4.addWidget(self.sp_IncDecAm)
        self.cb_IncDec = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.cb_IncDec.setObjectName(_fromUtf8("cb_IncDec"))
        self.cb_IncDec.addItem(_fromUtf8(""))
        self.cb_IncDec.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cb_IncDec)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Modify_Res/icons/img_IncDec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.box_RasCalc.addItem(self.IncDecLand, icon3, _fromUtf8(""))
        self.fillHoles = QtGui.QWidget()
        self.fillHoles.setGeometry(QtCore.QRect(0, 0, 469, 119))
        self.fillHoles.setObjectName(_fromUtf8("fillHoles"))
        self.helpText_4 = QtGui.QTextEdit(self.fillHoles)
        self.helpText_4.setGeometry(QtCore.QRect(290, 0, 171, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpText_4.sizePolicy().hasHeightForWidth())
        self.helpText_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.helpText_4.setFont(font)
        self.helpText_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.helpText_4.setFrameShape(QtGui.QFrame.WinPanel)
        self.helpText_4.setLineWidth(0)
        self.helpText_4.setMidLineWidth(0)
        self.helpText_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.helpText_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.helpText_4.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.helpText_4.setReadOnly(True)
        self.helpText_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.helpText_4.setObjectName(_fromUtf8("helpText_4"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Modify_Res/icons/img_closeHole.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.box_RasCalc.addItem(self.fillHoles, icon4, _fromUtf8(""))
        self.cleanPixel = QtGui.QWidget()
        self.cleanPixel.setObjectName(_fromUtf8("cleanPixel"))
        self.helpText_5 = QtGui.QTextEdit(self.cleanPixel)
        self.helpText_5.setGeometry(QtCore.QRect(290, 0, 171, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpText_5.sizePolicy().hasHeightForWidth())
        self.helpText_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.helpText_5.setFont(font)
        self.helpText_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.helpText_5.setFrameShape(QtGui.QFrame.WinPanel)
        self.helpText_5.setLineWidth(0)
        self.helpText_5.setMidLineWidth(0)
        self.helpText_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.helpText_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.helpText_5.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.helpText_5.setReadOnly(True)
        self.helpText_5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.helpText_5.setObjectName(_fromUtf8("helpText_5"))
        self.sp_CleanIter = QtGui.QSpinBox(self.cleanPixel)
        self.sp_CleanIter.setGeometry(QtCore.QRect(10, 30, 56, 25))
        self.sp_CleanIter.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sp_CleanIter.setPrefix(_fromUtf8(""))
        self.sp_CleanIter.setMinimum(1)
        self.sp_CleanIter.setProperty("value", 1)
        self.sp_CleanIter.setObjectName(_fromUtf8("sp_CleanIter"))
        self.label_2 = QtGui.QLabel(self.cleanPixel)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 151, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Modify_Res/icons/img_CleanRas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.box_RasCalc.addItem(self.cleanPixel, icon5, _fromUtf8(""))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(LandMod)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 471, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.where2Save = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.where2Save.setObjectName(_fromUtf8("where2Save"))
        self.horizontalLayout_2.addWidget(self.where2Save)
        self.btn_Save = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Save.sizePolicy().hasHeightForWidth())
        self.btn_Save.setSizePolicy(sizePolicy)
        self.btn_Save.setObjectName(_fromUtf8("btn_Save"))
        self.horizontalLayout_2.addWidget(self.btn_Save)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(LandMod)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 370, 471, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.addToToc = QtGui.QCheckBox(self.horizontalLayoutWidget_5)
        self.addToToc.setObjectName(_fromUtf8("addToToc"))
        self.horizontalLayout_5.addWidget(self.addToToc)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(self.horizontalLayoutWidget_5)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.line_2 = QtGui.QFrame(LandMod)
        self.line_2.setGeometry(QtCore.QRect(10, 360, 471, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))

        self.retranslateUi(LandMod)
        self.box_RasCalc.setCurrentIndex(0)
        self.box_RasCalc.layout().setSpacing(6)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), LandMod.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), LandMod.reject)
        QtCore.QMetaObject.connectSlotsByName(LandMod)

    def retranslateUi(self, LandMod):
        LandMod.setWindowTitle(QtGui.QApplication.translate("LandMod", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LandMod", "Class:", None, QtGui.QApplication.UnicodeUTF8))
        self.helpText.setHtml(QtGui.QApplication.translate("LandMod", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Extracts edges from each patch of the given class. Edge width can specified by multiplying the cellsize.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LandMod", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("LandMod", "Edge width", None, QtGui.QApplication.UnicodeUTF8))
        self.box_RasCalc.setItemText(self.box_RasCalc.indexOf(self.PatchEdges), QtGui.QApplication.translate("LandMod", "Extract landscape patch edges", None, QtGui.QApplication.UnicodeUTF8))
        self.helpText_2.setHtml(QtGui.QApplication.translate("LandMod", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Returns a raster with the greatest/smallest identified landcover patch. If multiple patches fullfill this criteria, than all of them are returned.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_MaxMin1.setText(QtGui.QApplication.translate("LandMod", "Smallest", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_MaxMin2.setText(QtGui.QApplication.translate("LandMod", "Greatest", None, QtGui.QApplication.UnicodeUTF8))
        self.box_RasCalc.setItemText(self.box_RasCalc.indexOf(self.IsoMaxMinPatch), QtGui.QApplication.translate("LandMod", "Isolate smallest or greatest patch", None, QtGui.QApplication.UnicodeUTF8))
        self.helpText_3.setHtml(QtGui.QApplication.translate("LandMod", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Let the user increase or decrease all landscape patches of a given class. The amount can be specified in the Spinbox.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sp_IncDecAm.setSuffix(QtGui.QApplication.translate("LandMod", " x", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_IncDec.setItemText(0, QtGui.QApplication.translate("LandMod", "Increase", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_IncDec.setItemText(1, QtGui.QApplication.translate("LandMod", "Decrease", None, QtGui.QApplication.UnicodeUTF8))
        self.box_RasCalc.setItemText(self.box_RasCalc.indexOf(self.IncDecLand), QtGui.QApplication.translate("LandMod", "Increase or decrease landscape patches", None, QtGui.QApplication.UnicodeUTF8))
        self.helpText_4.setHtml(QtGui.QApplication.translate("LandMod", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Closes holes (inner rings) in all patches of the specified landcover class</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.box_RasCalc.setItemText(self.box_RasCalc.indexOf(self.fillHoles), QtGui.QApplication.translate("LandMod", "Fill Holes inside landscape patches", None, QtGui.QApplication.UnicodeUTF8))
        self.helpText_5.setHtml(QtGui.QApplication.translate("LandMod", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Returns a raster with all pixels smaller than the structure removed. User can determine how many iterations should be performed.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sp_CleanIter.setSuffix(QtGui.QApplication.translate("LandMod", " x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LandMod", "Taxicab structure", None, QtGui.QApplication.UnicodeUTF8))
        self.box_RasCalc.setItemText(self.box_RasCalc.indexOf(self.cleanPixel), QtGui.QApplication.translate("LandMod", "Cleans landscape of small border pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.where2Save.setPlaceholderText(QtGui.QApplication.translate("LandMod", "Output file", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Save.setText(QtGui.QApplication.translate("LandMod", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.addToToc.setText(QtGui.QApplication.translate("LandMod", "Add result to QGis afterwards", None, QtGui.QApplication.UnicodeUTF8))

import res_PatchModify_rc
