# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caioh\src\LecoS\ui\dlg_PolygonPerLandCover.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BatchDialog(object):
    def setupUi(self, BatchDialog):
        BatchDialog.setObjectName("BatchDialog")
        BatchDialog.setWindowModality(QtCore.Qt.WindowModal)
        BatchDialog.resize(657, 574)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BatchDialog.sizePolicy().hasHeightForWidth())
        BatchDialog.setSizePolicy(sizePolicy)
        BatchDialog.setMinimumSize(QtCore.QSize(657, 574))
        BatchDialog.setMaximumSize(QtCore.QSize(657, 574))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icons/icon_batchCover.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BatchDialog.setWindowIcon(icon)
        self.line = QtWidgets.QFrame(BatchDialog)
        self.line.setGeometry(QtCore.QRect(10, 80, 641, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.SettingsBox = QtWidgets.QGroupBox(BatchDialog)
        self.SettingsBox.setGeometry(QtCore.QRect(10, 90, 671, 131))
        self.SettingsBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SettingsBox.setFlat(False)
        self.SettingsBox.setCheckable(False)
        self.SettingsBox.setObjectName("SettingsBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.SettingsBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 291, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rb_Landscape = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rb_Landscape.setChecked(True)
        self.rb_Landscape.setObjectName("rb_Landscape")
        self.horizontalLayout_3.addWidget(self.rb_Landscape)
        self.rb_Class = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rb_Class.setObjectName("rb_Class")
        self.horizontalLayout_3.addWidget(self.rb_Class)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.SettingsBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(330, 0, 311, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.ClassLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.ClassLayout.setContentsMargins(0, 0, 0, 0)
        self.ClassLayout.setObjectName("ClassLayout")
        self.LabelClass = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.LabelClass.setObjectName("LabelClass")
        self.ClassLayout.addWidget(self.LabelClass)
        self.cb_LClass = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.cb_LClass.setObjectName("cb_LClass")
        self.ClassLayout.addWidget(self.cb_LClass)
        self.label_3 = QtWidgets.QLabel(self.SettingsBox)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 221, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.SettingsBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 70, 641, 27))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ch_saveResult = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.ch_saveResult.setChecked(True)
        self.ch_saveResult.setObjectName("ch_saveResult")
        self.horizontalLayout_5.addWidget(self.ch_saveResult)
        spacerItem = QtWidgets.QSpacerItem(150, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.where2Save = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.where2Save.setFont(font)
        self.where2Save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.where2Save.setInputMask("")
        self.where2Save.setAlignment(QtCore.Qt.AlignCenter)
        self.where2Save.setObjectName("where2Save")
        self.horizontalLayout_5.addWidget(self.where2Save)
        self.locateDir = QtWidgets.QToolButton(self.horizontalLayoutWidget_5)
        self.locateDir.setObjectName("locateDir")
        self.horizontalLayout_5.addWidget(self.locateDir)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.SettingsBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 100, 641, 22))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ch_addToTable = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.ch_addToTable.setObjectName("ch_addToTable")
        self.horizontalLayout_6.addWidget(self.ch_addToTable)
        self.line_4 = QtWidgets.QFrame(self.SettingsBox)
        self.line_4.setGeometry(QtCore.QRect(300, 10, 20, 41))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.SettingsBox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(330, 30, 311, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LabelVector = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.LabelVector.setObjectName("LabelVector")
        self.horizontalLayout_7.addWidget(self.LabelVector)
        self.cb_SelD = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.cb_SelD.setObjectName("cb_SelD")
        self.horizontalLayout_7.addWidget(self.cb_SelD)
        self.horizontalLayoutWidget = QtWidgets.QWidget(BatchDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 641, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(312, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_Raster = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cb_Raster.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_Raster.setObjectName("cb_Raster")
        self.horizontalLayout.addWidget(self.cb_Raster)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(BatchDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 641, 34))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cb_Vector = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.cb_Vector.setObjectName("cb_Vector")
        self.horizontalLayout_2.addWidget(self.cb_Vector)
        self.line_2 = QtWidgets.QFrame(BatchDialog)
        self.line_2.setGeometry(QtCore.QRect(10, 520, 641, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(BatchDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 210, 641, 16))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(BatchDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 230, 234, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ClassMet = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ClassMet.setContentsMargins(0, 0, 0, 0)
        self.lay_ClassMet.setObjectName("lay_ClassMet")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.lay_ClassMet.addWidget(self.label_4)
        self.Cl_Metrics = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.Cl_Metrics.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Cl_Metrics.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Cl_Metrics.setLineWidth(1)
        self.Cl_Metrics.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Cl_Metrics.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Cl_Metrics.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.Cl_Metrics.setObjectName("Cl_Metrics")
        self.lay_ClassMet.addWidget(self.Cl_Metrics)
        self.ch_selectAll = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ch_selectAll.setObjectName("ch_selectAll")
        self.lay_ClassMet.addWidget(self.ch_selectAll)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(BatchDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 360, 163, 95))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.ch_div1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.ch_div1.setObjectName("ch_div1")
        self.verticalLayout_2.addWidget(self.ch_div1)
        self.ch_div2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.ch_div2.setObjectName("ch_div2")
        self.verticalLayout_2.addWidget(self.ch_div2)
        self.ch_div3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.ch_div3.setObjectName("ch_div3")
        self.verticalLayout_2.addWidget(self.ch_div3)
        self.gridLayoutWidget = QtWidgets.QWidget(BatchDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(250, 230, 391, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.LandscapeBox = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.LandscapeBox.setContentsMargins(0, 0, 0, 0)
        self.LandscapeBox.setObjectName("LandscapeBox")
        self.ch_LC4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC4.setObjectName("ch_LC4")
        self.LandscapeBox.addWidget(self.ch_LC4, 4, 0, 1, 1)
        self.ch_LC1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC1.setObjectName("ch_LC1")
        self.LandscapeBox.addWidget(self.ch_LC1, 1, 0, 1, 1)
        self.ch_LC2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC2.setObjectName("ch_LC2")
        self.LandscapeBox.addWidget(self.ch_LC2, 2, 0, 1, 1)
        self.ch_LC3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC3.setObjectName("ch_LC3")
        self.LandscapeBox.addWidget(self.ch_LC3, 3, 0, 1, 1)
        self.ch_LC5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC5.setObjectName("ch_LC5")
        self.LandscapeBox.addWidget(self.ch_LC5, 1, 1, 1, 1)
        self.ch_LC7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC7.setObjectName("ch_LC7")
        self.LandscapeBox.addWidget(self.ch_LC7, 3, 1, 1, 1)
        self.ch_LC6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC6.setObjectName("ch_LC6")
        self.LandscapeBox.addWidget(self.ch_LC6, 2, 1, 1, 1)
        self.ch_LC8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_LC8.setObjectName("ch_LC8")
        self.LandscapeBox.addWidget(self.ch_LC8, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.LandscapeBox.addWidget(self.label_6, 0, 0, 1, 1)
        self.ch_AddQGIS = QtWidgets.QCheckBox(BatchDialog)
        self.ch_AddQGIS.setGeometry(QtCore.QRect(10, 540, 301, 20))
        self.ch_AddQGIS.setChecked(True)
        self.ch_AddQGIS.setObjectName("ch_AddQGIS")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(BatchDialog)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(380, 530, 271, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_About = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_About.setIcon(icon1)
        self.btn_About.setIconSize(QtCore.QSize(12, 12))
        self.btn_About.setObjectName("btn_About")
        self.horizontalLayout_8.addWidget(self.btn_About)
        self.startButtons = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget_8)
        self.startButtons.setOrientation(QtCore.Qt.Horizontal)
        self.startButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.startButtons.setCenterButtons(True)
        self.startButtons.setObjectName("startButtons")
        self.horizontalLayout_8.addWidget(self.startButtons)
        self.label_2.setBuddy(self.label_2)

        self.retranslateUi(BatchDialog)
        self.startButtons.accepted.connect(BatchDialog.accept)
        self.startButtons.rejected.connect(BatchDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BatchDialog)
        BatchDialog.setTabOrder(self.cb_Raster, self.cb_Vector)
        BatchDialog.setTabOrder(self.cb_Vector, self.rb_Class)
        BatchDialog.setTabOrder(self.rb_Class, self.rb_Landscape)
        BatchDialog.setTabOrder(self.rb_Landscape, self.cb_LClass)
        BatchDialog.setTabOrder(self.cb_LClass, self.Cl_Metrics)
        BatchDialog.setTabOrder(self.Cl_Metrics, self.startButtons)

    def retranslateUi(self, BatchDialog):
        _translate = QtCore.QCoreApplication.translate
        BatchDialog.setWindowTitle(_translate("BatchDialog", "Polygon batch overlay"))
        self.SettingsBox.setTitle(_translate("BatchDialog", "Settings:"))
        self.rb_Landscape.setText(_translate("BatchDialog", "Landscape"))
        self.rb_Class.setText(_translate("BatchDialog", "Class"))
        self.LabelClass.setText(_translate("BatchDialog", "Choose class :"))
        self.label_3.setText(_translate("BatchDialog", "<html><head/><body><p>Output <span style=\" font-size:8pt; font-weight:400; font-style:italic;\">(unselect for direct output)</span>:</p></body></html>"))
        self.ch_saveResult.setText(_translate("BatchDialog", "Save in file:"))
        self.where2Save.setText(_translate("BatchDialog", "Select a destination or leave blank to create a temporary file"))
        self.locateDir.setText(_translate("BatchDialog", "..."))
        self.ch_addToTable.setText(_translate("BatchDialog", "Save in attribute table"))
        self.LabelVector.setText(_translate("BatchDialog", "Vector grid ID :"))
        self.label.setText(_translate("BatchDialog", "Landscape layer :"))
        self.label_2.setText(_translate("BatchDialog", "<html><head/><body><p>Overlaying grid :</p></body></html>"))
        self.label_4.setText(_translate("BatchDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Selected Metrics</span><br/><span style=\" font-size:9pt; font-style:italic;\">(press CTRL for multiple selections)</span></p></body></html>"))
        self.ch_selectAll.setText(_translate("BatchDialog", "Select all"))
        self.label_5.setText(_translate("BatchDialog", "Diversity"))
        self.ch_div1.setText(_translate("BatchDialog", "Shannon Index"))
        self.ch_div2.setText(_translate("BatchDialog", "Shannon equitability"))
        self.ch_div3.setText(_translate("BatchDialog", "Simpson Index"))
        self.ch_LC4.setText(_translate("BatchDialog", "Maximum"))
        self.ch_LC1.setText(_translate("BatchDialog", "Mean"))
        self.ch_LC2.setText(_translate("BatchDialog", "Sum"))
        self.ch_LC3.setText(_translate("BatchDialog", "Minimum"))
        self.ch_LC5.setText(_translate("BatchDialog", "Standard Deviation"))
        self.ch_LC7.setText(_translate("BatchDialog", "Median"))
        self.ch_LC6.setText(_translate("BatchDialog", "Lower Quantile (25%)"))
        self.ch_LC8.setText(_translate("BatchDialog", "Upper Quantile (25%)"))
        self.label_6.setText(_translate("BatchDialog", "Zonal statistics"))
        self.ch_AddQGIS.setText(_translate("BatchDialog", "Add table to QGIS afterwards"))
        self.btn_About.setText(_translate("BatchDialog", "About"))

from .resources_rc import *