# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caioh\src\LecoS\ui\dlg_RasterIndexer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RasterIndexer(object):
    def setupUi(self, RasterIndexer):
        RasterIndexer.setObjectName("RasterIndexer")
        RasterIndexer.resize(550, 406)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RasterIndexer.sizePolicy().hasHeightForWidth())
        RasterIndexer.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(RasterIndexer)
        self.buttonBox.setGeometry(QtCore.QRect(190, 370, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.methodSource = QtWidgets.QTextEdit(RasterIndexer)
        self.methodSource.setGeometry(QtCore.QRect(240, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.methodSource.setFont(font)
        self.methodSource.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.methodSource.setFrameShadow(QtWidgets.QFrame.Plain)
        self.methodSource.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.methodSource.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.methodSource.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.methodSource.setReadOnly(True)
        self.methodSource.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.methodSource.setObjectName("methodSource")
        self.line = QtWidgets.QFrame(RasterIndexer)
        self.line.setGeometry(QtCore.QRect(10, 50, 531, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(RasterIndexer)
        self.frame.setGeometry(QtCore.QRect(10, 70, 531, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 511, 31))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 511, 131))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 90, 511, 27))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sb_movWin = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.sb_movWin.setWrapping(False)
        self.sb_movWin.setFrame(True)
        self.sb_movWin.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_movWin.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sb_movWin.setSpecialValueText("")
        self.sb_movWin.setMinimum(3)
        self.sb_movWin.setSingleStep(2)
        self.sb_movWin.setObjectName("sb_movWin")
        self.horizontalLayout.addWidget(self.sb_movWin)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 511, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_Raster = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.cb_Raster.setObjectName("cb_Raster")
        self.horizontalLayout_2.addWidget(self.cb_Raster)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(10, 160, 511, 16))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 511, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 511, 34))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.le_where2save = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.le_where2save.setReadOnly(True)
        self.le_where2save.setObjectName("le_where2save")
        self.horizontalLayout_3.addWidget(self.le_where2save)
        self.btn_Save = QtWidgets.QToolButton(self.horizontalLayoutWidget_3)
        self.btn_Save.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btn_Save.setArrowType(QtCore.Qt.NoArrow)
        self.btn_Save.setObjectName("btn_Save")
        self.horizontalLayout_3.addWidget(self.btn_Save)
        self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(0, 70, 291, 20))
        self.checkBox.setObjectName("checkBox")
        self.groupBox_3 = QtWidgets.QGroupBox(RasterIndexer)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 0, 211, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cb_method = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_method.setGeometry(QtCore.QRect(0, 20, 211, 31))
        self.cb_method.setObjectName("cb_method")

        self.retranslateUi(RasterIndexer)
        self.buttonBox.accepted.connect(RasterIndexer.accept)
        self.buttonBox.rejected.connect(RasterIndexer.reject)
        QtCore.QMetaObject.connectSlotsByName(RasterIndexer)

    def retranslateUi(self, RasterIndexer):
        _translate = QtCore.QCoreApplication.translate
        RasterIndexer.setWindowTitle(_translate("RasterIndexer", "Dialog"))
        self.label_2.setText(_translate("RasterIndexer", "<html><head/><body><p>Creates a forest fragmentation index map after <a href=\"http://www.consecol.org/vol4/iss2/art3/\"><span style=\" text-decoration: underline; color:#0000ff;\">Riitters et al.</span></a></p></body></html>"))
        self.groupBox.setTitle(_translate("RasterIndexer", "Input"))
        self.label_4.setText(_translate("RasterIndexer", "Size of moving Window (odd number)"))
        self.label_3.setText(_translate("RasterIndexer", "<html><head/><body><p>Forest raster layer </p><p>(where forest=1, non-forest=0)</p></body></html>"))
        self.groupBox_2.setTitle(_translate("RasterIndexer", "Output"))
        self.btn_Save.setText(_translate("RasterIndexer", "..."))
        self.label_5.setText(_translate("RasterIndexer", "<html><head/><body><p>Where to save</p></body></html>"))
        self.checkBox.setText(_translate("RasterIndexer", "Append to table of contents afterwards"))
        self.groupBox_3.setTitle(_translate("RasterIndexer", "Method:"))

